[package]
name = "LostAndFoundRegistry"
version = "0.0.0"

[dependencies]
AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/aptos-framework", rev = "mainnet" }

[addresses]
my_addrx = "b566423fc7964b3b46672c6bd7a1ed2f9b761d2bb7da66fed07693dcb326315a"
sys_addrx="0xca10b0176c34f9a8315589ff977645e04497814e9753d21f7d7e7c3d83aa7b57"
std = "0x1"